name: Documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      # - name: Install sphinx-build
      #   run: |
      #     apt-get install python3-sphinx
      - name: Install dependencies
        run: |
          pip install -e '.[dev]'
      - name: Sphinx build
        run: |
          sphinx-build docs/source docs/build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/gh-pages' }}
        with:
          publish_branch: documentation
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
