name: Deploy Documentation


on:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Set up environment
        run: |
          npm install gitbook-cli -g

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Build documentation
        run: |
          cd ./docs
          sphinx-apidoc -f -o source/ ../masterplan_tools/
          make html
          cd ..

      - name: Commit and push changes
        run: |
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add .
          git commit -m "Update documentation"
          git push origin ${{ github.event.pull_request.base.ref }}

      - name: Deploy GitBook
        run: |
          gitbook-cli publish ./docs/build/html
