SQUARE_METERS_IN_HECTARE = 10_000

BUILDING_TYPES = [
    # residential
    "apartments",
    "barracks",
    "bungalow",
    "cabin",
    "detached",
    "dormitory",
    "farm",
    "ger",
    "hotel",
    "house",
    "houseboat",
    "residential",
    "semidetached_house",
    "static_caravan",
    "stilt_house",
    "terrace",
    "tree_house",
    "trullo",
    # commercial
    "commercial",
    "industrial",
    "kiosk",
    "office",
    "retail",
    "supermarket",
    "warehouse",
    # religious
    "religious",
    "cathedral",
    "chapel",
    "church",
    "kingdom_hall",
    "monastery",
    "mosque",
    "presbytery",
    "shrine",
    "synagogue",
    "temple",
    # public
    "bakehouse",
    "bridge",
    "civic",
    "college",
    "fire_station",
    "government",
    "gatehouse",
    "hospital",
    "kindergarten",
    "museum",
    "public",
    "school",
    "toilets",
    "train_station",
    "transportation",
    "university",
    # agricultural
    "barn",
    "conservatory",
    "cowshed",
    "farm_auxiliary",
    "greenhouse",
    "slurry_tank",
    "stable",
    "sty",
    "livestock",
    # sport
    "grandstand",
    "pavilion",
    "riding_hall",
    "sports_hall",
    "sports_centre",
    "stadium",
    # storage
    "allotment_house",
    "boathouse",
    "hangar",
    "hut",
    "shed",
    # cars
    "carport",
    "garage",
    "garages",
    "parking",
    # energy and technical
    "digester",
    "service",
    "tech_cab",
    "transformer_tower",
    "water_tower",
    "storage_tank",
    "silo",
    # other
    "beach_hut",
    "bunker",
    "castle",
    "construction",
    "container",
    "guardhouse",
    "military",
    "outbuilding",
    "pagoda",
    "quonset_hut",
    "roof",
    "ruins",
    "tent",
    "tower",
    "windmill",
]

FLOORS_DEFAULTS = {
    # residential
    "apartments": 9,
    "barracks": 5,
    "bungalow": 1,
    "cabin": 2,
    "detached": 2,
    "dormitory": 9,
    "farm": 2,
    "ger": 1,
    "hotel": 4,
    "house": 2,
    "houseboat": 1,
    "residential": 9,
    "semidetached_house": 2,
    "static_caravan": 1,
    "stilt_house": 1,
    "terrace": 2,
    "tree_house": 1,
    "trullo": 1,
    # commercial
    "commercial": 4,
    "industrial": 2,
    "kiosk": 1,
    "office": 9,
    "retail": 1,
    "supermarket": 1,
    "warehouse": 1,
    # religious
    "religious": 1,
    "cathedral": 2,
    "chapel": 1,
    "church": 2,
    "kingdom_hall": 1,
    "monastery": 2,
    "mosque": 2,
    "presbytery": 2,
    "shrine": 1,
    "synagogue": 2,
    "temple": 1,
    # public
    "bakehouse": 1,
    "bridge": 1,
    "civic": 2,
    "college": 4,
    "fire_station": 2,
    "government": 3,
    "gatehouse": 1,
    "hospital": 4,
    "kindergarten": 3,
    "museum": 2,
    "public": 2,
    "school": 3,
    "toilets": 1,
    "train_station": 1,
    "transportation": 1,
    "university": 4,
    # agricultural
    "barn": 1,
    "conservatory": 1,
    "cowshed": 1,
    "farm_auxiliary": 1,
    "greenhouse": 1,
    "slurry_tank": 0,
    "stable": 1,
    "sty": 1,
    "livestock": 1,
    # sport
    "grandstand": 2,
    "pavilion": 2,
    "riding_hall": 1,
    "sports_hall": 2,
    "sports_centre": 2,
    "stadium": 2,
    # storage
    "allotment_house": 1,
    "boathouse": 1,
    "hangar": 1,
    "hut": 1,
    "shed": 1,
    # cars
    "carport": 1,
    "garage": 1,
    "garages": 1,
    "parking": 2,
    # energy and technical
    "digester": 0,
    "service": 1,
    "tech_cab": 1,
    "transformer_tower": 0,
    "water_tower": 0,
    "storage_tank": 0,
    "silo": 0,
    # other
    "beach_hut": 1,
    "bunker": 1,
    "castle": 2,
    "construction": 0,
    "container": 1,
    "guardhouse": 1,
    "military": 2,
    "outbuilding": 1,
    "pagoda": 3,
    "quonset_hut": 1,
    "roof": 1,
    "ruins": 0,
    "tent": 1,
    "tower": 3,
    "windmill": 2,
}

FLATS_PER_FLOOR = {
    "apartments": 6,
    "dormitory": 16,
    "hotel": 20,
    "residential": 6,
}
TOTAL_FLATS = {
    "barracks": 0,
    "bungalow": 1,
    "cabin": 0,
    "detached": 1,
    "farm": 1,
    "ger": 1,
    "house": 1,
    "houseboat": 1,
    "semidetached_house": 2,
    "static_caravan": 1,
    "stilt_house": 1,
    "terrace": 0,
    "tree_house": 1,
    "trullo": 1,
}

LIVING_BUILDING_TYPES = [
    "apartments",
    "barracks",
    "bungalow",
    "cabin",
    "detached",
    "dormitory",
    "farm",
    "ger",
    "hotel",
    "house",
    "houseboat",
    "residential",
    "semidetached_house",
    "static_caravan",
    "stilt_house",
    "terrace",
    "tree_house",
    "trullo",
]
